language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "J2cyLnnR6eJ02Wvf8MF6qEKeakRv1xu8bW/vISvECXRMcemN+8/jMXxsh8l0sVE2ah0uJOB5RXUd59Xm8cYyPvKbOOlFm6KqAWlYjwn0Pp
IUpKACbcLMYfsG5XBWZFUbWJ6550BcWOnSkfAoJvzrtPt9v+AyF2eia5vVB/7zOhjvAbWIadQiQ9Oi1OUVl5x0gXY4ymrcy88Vcd9TCh6uVTpS9Ym3jnU
Hfy7LlHv4+UXhuVKXwGM2gdApw3miMmKBc8BQa83w1jQ1qd0Ve3+vTY9h5wf2UWVuKZaeIfbPZy37iiiMsML8sX6RO4HkwBmguJWK/aXddJfporgx9xP4
j4gq/X5/JGG10OlCjfzvCKXtzBOPqEod6ALjy32a/HlCCpYMCgm7NONmxVFOWvVHkS+qNped3fN0xIMNTyZB4536SubAnCbzWKVx0XlzXfJyFngiMhoz9
sPFMeAEIW4r+HK+hWHy9U24X6wjiQazrGT+kPSsMyByXewErbNa+3ASe6eNWzsJmo/d88i+d17YsL9P/cUdQitShZopkp25+KCbXJgoz4rYibdDe7qJgm
x6jVM6YzYYN7inO7C1QgfWJrjHtWa37v3eOoLYDNA+afs0jLwHo+7rtZVe0m4Uwz/37+HV4h/XMCoBALS66enaZZ9zT8P9SX1pWQk5Wt8BsxU="

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  
cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: test
      jdk: oraclejdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: oraclejdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
